In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Womens Clothing E-Commerce Reviews.csv")

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df.shape

(23486, 11)

In [6]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [7]:
df[df['Review Text']==""]=np.NaN

In [8]:
df['Review Text'].fillna("No Review",inplace=True)

In [9]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [10]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

# Define Target(y) and Feature(X)bold **text**

In [11]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [12]:
X=df['Review Text']

In [13]:
y=df['Rating']

In [14]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=0)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to **Tokens**

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [20]:
X_train=cv.fit_transform(X_train)

In [21]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 dress', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [22]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X_test=cv.fit_transform(X_test)

In [24]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 bought', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [25]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model **Train**

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model=MultinomialNB()

In [30]:
model.fit(X_train,y_train)

MultinomialNB()

# Get Model **Prediction**

In [31]:
y_pred=model.predict(X_test)

In [32]:
y_pred.shape

(7046,)

In [33]:
y_pred

array([5., 2., 5., ..., 1., 3., 5.])

# Get Probability of Each Predicted **Class**

In [34]:
model.predict_proba(X_test)

array([[0.08419981, 0.17144196, 0.06766736, 0.2188427 , 0.45784817],
       [0.22335164, 0.35688045, 0.0266629 , 0.05126105, 0.34184395],
       [0.0972426 , 0.00596862, 0.35831458, 0.06886702, 0.46960718],
       ...,
       [0.36565805, 0.26557252, 0.05591893, 0.04252073, 0.27032976],
       [0.17200924, 0.01911023, 0.53617855, 0.22040163, 0.05230035],
       [0.10392364, 0.2524783 , 0.02507605, 0.06041559, 0.55810642]])

# Get Model **Evaluation**

In [35]:
from sklearn.metrics import confusion_matrix, classification_report

In [36]:
print(confusion_matrix(y_test,y_pred))

[[  21   21   29   30  145]
 [  55   55   60   74  238]
 [  96   92  130  137  398]
 [ 161  103  157  304  747]
 [ 376  241  338  657 2381]]


In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.09      0.04       246
         2.0       0.11      0.11      0.11       482
         3.0       0.18      0.15      0.17       853
         4.0       0.25      0.21      0.23      1472
         5.0       0.61      0.60      0.60      3993

    accuracy                           0.41      7046
   macro avg       0.24      0.23      0.23      7046
weighted avg       0.43      0.41      0.42      7046



# Recategories Ratings as Poor (0) and Good **bold text**(1)

In [38]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [39]:
y=df['Rating']

In [40]:
x=df['Review Text']

# Train Test **Split**

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=0)

In [43]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to **Tokens**

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [46]:
X_train=cv.fit_transform(X_train)

In [47]:
X_test=cv.fit_transform(X_test)

# Get Model Re-**Train**

In [48]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
model=MultinomialNB()

In [50]:
model.fit(X_train,y_train)

MultinomialNB()

# Get Model **Prediction**

In [51]:
y_pred=model.predict(X_test)

In [52]:
y_pred.shape

(7046,)

In [53]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

# Get Moel **Evaluation**

In [55]:
from sklearn.metrics import confusion_matrix,classification_report

In [58]:
print(confusion_matrix(y_test,y_pred))

[[ 424 1157]
 [ 841 4624]]


In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.34      0.27      0.30      1581
         1.0       0.80      0.85      0.82      5465

    accuracy                           0.72      7046
   macro avg       0.57      0.56      0.56      7046
weighted avg       0.70      0.72      0.70      7046

